#!/usr/bin/env python3

import sys
from math import isqrt


def factorize(n):
    """Return a factorization of n into two smaller factors."""
    for b in range(2, isqrt(n) + 1):
        if n % b == 0:
            return f"{n}={b}*{n//b}"
    return f"{n} is prime"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        for line in f:
            n = int(line.strip())
            print(factorize(n))
